apiVersion: v1
data:
  ns: {{ .Values.ns }}
  clusterName: {{ .Values.clusterName }}
kind: ConfigMap
metadata:
  labels:
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{ template "fullname" . }}-fake-tiller'
